name: wallhaven
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'        # Dart 版本：只要是 3.0 以上都行
  flutter: '>=3.10.7'          # Flutter 版本：要求 3.10.7 以上（这行是可选的）

dependencies:
  flutter:
    sdk: flutter
  
  # 多语言支持 (main.dart 需要用到)
  flutter_localizations:
    sdk: flutter

  # 默认图标
  cupertino_icons: ^1.0.6
  
  # 瀑布流布局
  flutter_staggered_grid_view: ^0.7.0
  
  # 网络请求
  dio: ^5.4.0
  
  # 权限处理
  permission_handler: ^11.3.0
  
  # 保存图片
  gal: ^2.3.0
  
  # 状态管理
  provider: ^6.1.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 动态取色 (Material You)
  dynamic_color: ^1.6.9
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
